#!/usr/bin/env bash

apt update
apt install -y \
    git \
    curl \
    vim \
    libssl-dev \
    build-essential \
    python3 \
    bzip2 \
    wget
update-alternatives --install /usr/bin/python python /usr/bin/python3 1
