#!/usr/bin/env bash

cmake_version=3.23.0
cmake=cmake-${cmake_version}-linux-x86_64.sh

echo "INSTALL CMAKE"
wget -nv https://github.com/Kitware/CMake/releases/download/v${cmake_version}/${cmake}
chmod +x ${cmake}
./${cmake} --skip-license
rm ${cmake}
cmake --version

apt install -y ninja-build

echo "INSTALL SOLANA RUST"
git clone --single-branch https://github.com/solana-labs/bpf-tools.git
./bpf-tools/build.sh
rm -rf bpf-tools
