#!/usr/bin/env bash

# build image
source ./devops/tools/git-vars $1 $2
ARGS="${@:3}"

docker buildx build ${ARGS} \
    -f devops/images/${IMAGE}/Dockerfile \
    -o type=docker \
    --cache-from ${DOCKER_REPO} \
    -t ${REPO_NAME} -t ${DOCKER_REPO} .
