#!/usr/bin/env bash
# set -xv

# Build multi-arch image and push to docker repo
source ./devops/tools/git-vars $1 $2
ARGS="${@:3}"

REPOTAGS="-t ${DOCKER_REPO}:${GIT_COMMIT}"

if [[ ${GIT_BRANCH} == master ]]; then
    REPOTAGS="${REPOTAGS} -t ${DOCKER_REPO}:latest"
fi

docker buildx build ${ARGS}\
    -f devops/images/${IMAGE}/Dockerfile \
    -o type=registry \
    --cache-from ${DOCKER_REPO} \
    --platform linux/amd64,linux/arm64 \
    ${REPOTAGS} .
