#!/usr/bin/env bash

# IMPORTANT! DOCKER_URL must be set by the calling script

GIT_BRANCH=`git symbolic-ref HEAD --short 2>/dev/null`
if [ "$GIT_BRANCH" = "" ] ; then
    GIT_BRANCH=`git branch -a --contains HEAD | sed -n 2p | awk '{ printf $1 }'`
    GIT_BRANCH=${GIT_BRANCH#remotes/origin/}
fi

GIT_MESSAGE=`git log -1 --pretty=%B`
GIT_AUTHOR=`git log -1 --pretty=%an`
GIT_AUTHOR_EMAIL=`git log -1 --pretty=%ae`
GIT_COMMIT=`git log -1 --pretty=%H`

# first argument is the directory of the image
IMAGE=$1
# first argument is the directory of the image
NAME=${IMAGE}
# second optional parameter is the repo name if different from the image name
REPO_NAME=${2:-${NAME}}
# full url of docker repo
DOCKER_REPO=${DOCKER_URL}/${REPO_NAME}

echo "repository: ${DOCKER_REPO}"
