#!/usr/bin/env bash
set -e

TA_LIB_VERSION=0.4.0

wget -nv https://prdownloads.sourceforge.net/ta-lib/ta-lib-${TA_LIB_VERSION}-src.tar.gz
tar -xzf ta-lib-${TA_LIB_VERSION}-src.tar.gz
cd ta-lib
rm -rf config.*
wget -nv 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD' -O config.guess
wget -nv 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD' -O config.sub
./configure --prefix=/usr
make
make install
cd ..
rm -rf ta-li*
