#!/usr/bin/env bash
set -e

INSTALLATION_PATH=${FG_PATH:-/bin}

wget -nv https://raw.githubusercontent.com/brendangregg/FlameGraph/master/flamegraph.pl -O ${INSTALLATION_PATH}/flamegraph.pl
chmod +x ${INSTALLATION_PATH}/flamegraph.pl
