#!/usr/bin/env bash
#
touch ${PWD}/.local.env
touch ${PWD}/.env

docker run --rm \
    -v ${PWD}:/solare \
    -v ${HOME}/.config:${HOME}/.config \
    --env-file ${PWD}/.env \
    --env-file ${PWD}/.local.env \
    --network solare_default \
    solare $@
